version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - API_KEY=ENTER_YOUR_API_KEY_HERE
      - BASE_URL=https://api.openweathermap.org/data/2.5
    volumes:
      - ./backend:/usr/src/app
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BASE_API_URL=http://backend:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    restart: always
